export { HeroSection } from './hero/HeroSection'
export { AboutSection } from './about'
export { SkillsSection } from './skills'
export { WorksSection } from './works'
export { ContactSection } from './contact/ContactSection'
